### ISSUE TITLE
Design Custom Controller Using HTC Vive Tracker

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/VRIT#4]
Begin the design and use case for a custom controller that utilizes the HTC Vive Tracker.

**Comment by gavinjalberghini** [comment]
As a result of the 8/31 meeting, we have decided to work on a virtual HEMA environment. Use that information when coming up with a custom controller.

**Comment by SeekingExCalibur** [comment]
We found a Monopod which has a screw that matches the specifications of the HTC tracker. We will begin testing with it to determine ideal placement of tracker on monopod to best manipulate the values in unity

**Comment by SeekingExCalibur** [comment]
We are also Beginning to create models in Solid Works to eventually 3D print for the controller.

**Comment by gavinjalberghini** [comment]
Closing this issue because the basic tracked monopod is finished and ready for testing.
